const initialState = {
  user: {
    firstname: "Alisher",
    lastname: "Urolov",
    username: "aliwerdev",
    email: "aliwerdev@gmail.com",
    password: "23456789",
    profile_pic:
      "https://avatars.githubusercontent.com/u/94689030?v=4",
    bio: "I am a software engineer",
    location: "San Francisco, CA",
    website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
    followers: [],
    following: [],
    posts: [],
  },
  followers: [
    {
      id: 1,
      firstname: "Joe",
      lastname: "Bosh",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 1,
      firstname: "Joe",
      lastname: "Bosh",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 2,
      firstname: "Uiliam",
      lastname: "Richard",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 3,
      firstname: "Dince",
      lastname: "Wor",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 1,
      firstname: "Joe",
      lastname: "Bosh",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 1,
      firstname: "Joe",
      lastname: "Bosh",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 2,
      firstname: "Uiliam",
      lastname: "Richard",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 3,
      firstname: "Dince",
      lastname: "Wor",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 1,
      firstname: "Joe",
      lastname: "Bosh",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 1,
      firstname: "Joe",
      lastname: "Bosh",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 2,
      firstname: "Uiliam",
      lastname: "Richard",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
    {
      id: 3,
      firstname: "Dince",
      lastname: "Wor",
      email: "joe@gmail.com",
      password: "joe",
      profile_pic:
        "https://images.unsplash.com/photo-1518806118471-f28b20a1d79d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60",
      bio: "I am a software engineer",
      location: "San Francisco, CA",
      website: "https://www.linkedin.com/in/joe-bosh-a8a8b814a/",
      followers: [],
      following: [],
      posts: [],
    },
  ],
  following: [],
};

const usersReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state;
  }
};

export default usersReducer;
