<<<<<<< HEAD
import Head from "next/head";
import Header from "../components/header";
=======
import { Box } from "@mui/material";
>>>>>>> c1e5e798ba0adce6ba74a9a3ff80b332205634db
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
<<<<<<< HEAD
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
=======

>>>>>>> c1e5e798ba0adce6ba74a9a3ff80b332205634db
    </div>
  );
}
